// This directive indicates that this file should be executed on the client-side in Next.js App Router.
// It ensures that client-only features (like hooks) are handled properly.
"use client";

// Import the Metadata type from Next.js for defining page metadata.
// This is used for SEO and page configuration, though it's commented out here.
import type { Metadata } from "next";

// Import custom fonts from Google Fonts via Next.js font optimization.
// Geist and Geist_Mono are modern sans-serif and monospace fonts, respectively.
import { Geist, Geist_Mono } from "next/font/google";

// Import global CSS styles for the application.
// This file likely contains base styles, resets, or custom CSS.
import "./globals.css";

// Import ThemeProvider and createTheme from Material-UI (MUI) for theming.
// ThemeProvider wraps the app to apply a consistent theme, and createTheme generates a custom theme object.
import { ThemeProvider, createTheme } from "@mui/material/styles";

// Import CssBaseline from MUI to apply global CSS resets.
// This ensures consistent styling across browsers by normalizing elements like margins and fonts.
import CssBaseline from "@mui/material/CssBaseline";

// Import SessionProvider from next-auth/react for handling authentication sessions.
// This provider makes session data available to child components via hooks like useSession.
import { SessionProvider } from "next-auth/react";

// Import AppRouterCacheProvider from MUI's Next.js integration package.
// This handles Emotion cache for server-side rendering (SSR) and hydration in App Router, preventing style mismatches.
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

// Create a default MUI theme using createTheme().
// This can be customized later with options like colors, typography, etc. Here, it's using defaults.
const theme = createTheme();

// Configure the Geist sans-serif font with Next.js font optimization.
// 'variable' sets a CSS variable for easy use, 'subsets' limits to Latin characters for performance.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Configure the Geist monospace font similarly.
// This is useful for code blocks or technical text.
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// This exports metadata for the app (commented out).
// It would set the page title and description for SEO, but it's disabled here.
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// The default export: RootLayout component, which wraps all pages in the App Router.
// It receives 'children' (the page content) as a prop.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Type for children: any React node (e.g., pages or components).
}>) {
  return (
    // The root <html> element with language set to English.
    // This is the top-level wrapper for the entire document.
    <html lang="en">
      {/* The <body> element with class names applying the custom fonts. */}
       {/* 'antialiased' enables font smoothing for better readability. */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap the app with SessionProvider for authentication context.
        This makes session data available throughout the app. */}
        <SessionProvider>
          {/* Wrap with ThemeProvider to apply the MUI theme.
          All child components can now use themed styles. */}
          <ThemeProvider theme={theme}>
            {/* Wrap with AppRouterCacheProvider for handling MUI styles in Next.js App Router.
            This ensures SSR and client hydration match, avoiding errors. */}
            <AppRouterCacheProvider>
              {/* Include CssBaseline for global style normalization.
              This should be near the root to apply resets early. */}
              <CssBaseline />
              {/* Render the children (the actual page content). */}
              {children}{" "}
            </AppRouterCacheProvider>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}